"""Initial migration

Revision ID: ea4887199e8f
Revises: 25a68947b137
Create Date: 2025-03-28 15:49:23.224706

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea4887199e8f'
down_revision: Union[str, None] = '25a68947b137'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('balances', sa.Column('bandwidth', sa.Integer(), nullable=False))
    op.add_column('balances', sa.Column('energy', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('balances', 'energy')
    op.drop_column('balances', 'bandwidth')
    # ### end Alembic commands ###
